### ISSUE TITLE
Help needed for something similar

### ISSUE THREAD

**Issue by ipochi** [eReuse/workbench-live#1]
@bustawin 

Hi I followed your blog post and the manual for live-build for a similar purpose.
I was hoping you'd point me in the right direction and bit of help.

My requirement is to have a custom script / ncurses application run right after the bootup prompt or there is no prompt for login user and directly my program/script runs , doesn't matter

Once the program is running , it will need user interaction.
Upon user input , the script/program will proceed based on the user input and then proceed to completion either by suggesting reboot or just an echo that script finished sucessfully.

In essence, in a live cd where you have that installer option to install the OS.
I dont want that, rather my own program/script to run.

Thanks for the help !!

**Comment by bustawin** [comment]
Your use case is quite similar to ours (we execute a python terminal script after the ISO loads), so you can follow the majority of the tutorial, even fork this project and just change what you need. [Here](https://github.com/eReuse/workbench-live/blob/master/config/includes.chroot/home/user/.profile) is where we execute our software after loading the OS and [here](https://github.com/eReuse/workbench-live/blob/master/config/hooks/live/0100-workbench.hook.chroot) where we install our software when generating the ISO.

Let me close this and continue the conversation in the comments section of the [blog post](https://www.bustawin.com/create-a-custom-live-debian-9-the-pro-way/), as this discussion is not related to the project itself :-) Just answer me in the blog with a link to this issue.
